name: Publish

on:
  release:
    types:
      - created
  repository_dispatch:
    types: [publish]

jobs:
  publish:
    name: Publish to Github Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      
      - name: Install semantic-release plugins
        run: npm i --no-save @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits
      
      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@azzurri-group"

      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
